#requires -Version 5.1
#requires -Modules ActiveDirectory
[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='Medium')]
param([string]$ToolkitRoot=(Split-Path $PSScriptRoot -Parent),[switch]$SkipReportRefresh,[switch]$PassThru)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';Import-Module ActiveDirectory;Import-Module (Join-Path $ToolkitRoot 'modules\IAM-Common.psm1') -Force
$requestPath=Join-Path $ToolkitRoot 'input\JML-Requests.csv';$rbacPath=Join-Path $ToolkitRoot 'input\RBAC-Mapping.csv';$logDir=Join-Path $ToolkitRoot 'logs';Initialize-IAMLogFiles $logDir;$executionID=[guid]::NewGuid().Guid;$start=Get-Date;$operator=Get-IAMOperator;$requests=@();$processed=0;$success=0;$failure=0;$skipped=0;$refresh='NotRun';$results=@()
try{$requests=@(Import-Csv $requestPath|Where-Object {$_.Action -eq 'Mover' -and $_.ApprovalStatus -eq 'Approved'});$maps=Get-IAMRbacMappings $rbacPath
 foreach($r in $requests){$step='Validation';$sam=$r.SamAccountName;try{if(Test-IAMRequestAlreadyCompleted $r.RequestID (Join-Path $logDir 'JML-Audit.csv')){$skipped++;continue};if([string]::IsNullOrWhiteSpace($r.Department)){throw 'Target Department is blank.'};$user=Resolve-IAMUser $r.EmployeeID $r.SamAccountName;$sam=$user.SamAccountName;$target=Get-IAMRbacMapping $r.Department $maps;$manager=Resolve-IAMManager $r.Manager;$oldOU=Get-IAMParentDN $user.DistinguishedName;$oldManager=if($user.Manager){(Get-ADUser $user.Manager).Name}else{''};$oldAccess=Get-IAMMappedAccess $user $maps;$oldGroups=@($oldAccess.DepartmentGroup);$remove=@($oldAccess|Where-Object DepartmentGroup -ne $target.DepartmentGroup)
  if($PSCmdlet.ShouldProcess($sam,"Move from '$($user.Department)' to '$($r.Department)', update RBAC and shared-folder entitlement")){$processed++;foreach($m in $remove){$step="Remove $($m.DepartmentGroup)";Remove-ADGroupMember $m.DepartmentGroup $user -Confirm:$false;Write-IAMLog $logDir 'RBAC-Changes.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;Action='Mover';GroupName=$m.DepartmentGroup;ChangeType='Removed';PreviousDepartment=$user.Department;Department=$r.Department;MappedDriveRoot=$m.MappedDriveRoot;EntitledFolder=$m.EntitledFolder;AccessLevel=$m.AccessLevel;AccessType=$m.AccessType;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}};$already=$target.DepartmentGroup -in (Get-IAMGroupNames $user);if(-not $already){$step='Add target group';Add-ADGroupMember $target.DepartmentGroup $user;Write-IAMLog $logDir 'RBAC-Changes.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;Action='Mover';GroupName=$target.DepartmentGroup;ChangeType='Added';PreviousDepartment=$user.Department;Department=$r.Department;MappedDriveRoot=$target.MappedDriveRoot;EntitledFolder=$target.EntitledFolder;AccessLevel=$target.AccessLevel;AccessType=$target.AccessType;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}}
   $step='Update attributes';$set=@{Identity=$user;Department=$r.Department};if($r.JobTitle){$set.Title=$r.JobTitle};if($manager){$set.Manager=$manager.DistinguishedName};Set-ADUser @set;if($oldOU -ne $target.OU){$step='Move OU';Move-ADObject $user.DistinguishedName -TargetPath $target.OU}
   $removed=$remove.DepartmentGroup -join '; ';$prevFolders=$oldAccess.EntitledFolder -join '; ';Write-IAMLog $logDir 'Mover-Report.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;PreviousDepartment=$user.Department;Department=$r.Department;PreviousJobTitle=$user.Title;JobTitle=$r.JobTitle;PreviousManager=$oldManager;Manager=if($manager){$manager.Name}else{$oldManager};PreviousOU=$oldOU;TargetOU=$target.OU;RemovedGroups=$removed;AssignedGroups=$target.DepartmentGroup;PreviousEntitledFolders=$prevFolders;EntitledFolders=$target.EntitledFolder;DepartmentMappedDriveRoot=$target.MappedDriveRoot;DepartmentDriveLetter=$target.DepartmentDriveLetter;SharedDriveAccess=$target.AccessLevel;HomeDirectory=$user.HomeDirectory;HomeDrive=$user.HomeDrive;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending';Status='Success'};Write-IAMLog $logDir 'JML-Audit.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;UserPrincipalName=$user.UserPrincipalName;Action='Mover';ApprovalStatus=$r.ApprovalStatus;PreviousDepartment=$user.Department;Department=$r.Department;PreviousJobTitle=$user.Title;JobTitle=$r.JobTitle;PreviousManager=$oldManager;Manager=if($manager){$manager.Name}else{$oldManager};PreviousOU=$oldOU;TargetOU=$target.OU;AssignedGroups=$target.DepartmentGroup;RemovedGroups=$removed;DepartmentMappedDriveRoot=$target.MappedDriveRoot;PreviousEntitledFolders=$prevFolders;EntitledFolders=$target.EntitledFolder;SharedDriveAccess=$target.AccessLevel;HomeFolder=$user.HomeDirectory;HomeDrive=$user.HomeDrive;Status='Success';Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending'};$success++;$results+=[pscustomobject]@{RequestID=$r.RequestID;SamAccountName=$sam;PreviousDepartment=$user.Department;Department=$r.Department;RemovedGroups=$removed;AssignedGroup=$target.DepartmentGroup;EntitledFolder=$target.EntitledFolder;Status='Success'}
  }else{$skipped++}
 }catch{$failure++;$msg=$_.Exception.Message;Write-IAMLog $logDir 'Script-Errors.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;ScriptName='Invoke-Mover.ps1';Action='Mover';ErrorType=$_.Exception.GetType().FullName;ErrorMessage=$msg;FailedStep=$step;ComputerName=$env:COMPUTERNAME;Technician=$operator};Write-Error $msg}}
 if($success -gt 0 -and -not $WhatIfPreference -and -not $SkipReportRefresh){$refresh=Invoke-IAMReportRefresh $ToolkitRoot}else{$refresh=if($WhatIfPreference){'WhatIf-NoRefresh'}else{'NotRequired'}}
}finally{$end=Get-Date;$result=if($failure){'CompletedWithErrors'}elseif($WhatIfPreference){'WhatIfCompleted'}else{'Success'};Write-IAMLog $logDir 'Execution-History.csv' @{ExecutionID=$executionID;ScriptName='Invoke-Mover.ps1';StartTime=$start.ToString('o');EndTime=$end.ToString('o');DurationSeconds=[math]::Round(($end-$start).TotalSeconds,2);ComputerName=$env:COMPUTERNAME;Technician=$operator;WhatIfMode=[bool]$WhatIfPreference;RequestsFound=$requests.Count;RequestsProcessed=$processed;SuccessCount=$success;FailureCount=$failure;SkippedCount=$skipped;ReportRefreshResult=$refresh;Result=$result}}
if($PassThru){$results}
