#requires -Version 5.1
#requires -Modules ActiveDirectory
[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([string]$ToolkitRoot=(Split-Path $PSScriptRoot -Parent),[switch]$RemoveAllDirectGroups,[string[]]$ProtectedGroups=@('Domain Users'),[switch]$ClearManager,[switch]$ClearHomeDriveMapping,[switch]$SkipReportRefresh,[switch]$PassThru)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';Import-Module ActiveDirectory;Import-Module (Join-Path $ToolkitRoot 'modules\IAM-Common.psm1') -Force;$config=Import-IAMToolkitConfig -Path (Join-Path $ToolkitRoot 'config\IAM-Toolkit-Config.psd1')
$requestPath=Join-Path $ToolkitRoot 'input\JML-Requests.csv';$rbacPath=Join-Path $ToolkitRoot 'input\RBAC-Mapping.csv';$logDir=Join-Path $ToolkitRoot 'logs';Initialize-IAMLogFiles $logDir;$executionID=[guid]::NewGuid().Guid;$start=Get-Date;$operator=Get-IAMOperator;$requests=@();$processed=0;$success=0;$failure=0;$skipped=0;$refresh='NotRun';$results=@()
try{Get-ADOrganizationalUnit $config.DisabledUsersOU|Out-Null;$requests=@(Import-Csv $requestPath|Where-Object {$_.Action -eq 'Leaver' -and $_.ApprovalStatus -eq 'Approved'});$maps=Get-IAMRbacMappings $rbacPath
 foreach($r in $requests){$step='Validation';$sam=$r.SamAccountName;try{if(Test-IAMRequestAlreadyCompleted $r.RequestID (Join-Path $logDir 'JML-Audit.csv')){$skipped++;continue};$user=Resolve-IAMUser $r.EmployeeID $r.SamAccountName;$sam=$user.SamAccountName;$oldOU=Get-IAMParentDN $user.DistinguishedName;$oldManager=if($user.Manager){(Get-ADUser $user.Manager).Name}else{''};$mapped=Get-IAMMappedAccess $user $maps;$direct=@($user.MemberOf|ForEach-Object{Get-ADGroup $_});$remove=if($RemoveAllDirectGroups){@($direct|Where-Object Name -notin $ProtectedGroups)}else{@($direct|Where-Object Name -in $maps.DepartmentGroup)}
  if($PSCmdlet.ShouldProcess($sam,'Disable account, reset password, revoke RBAC/shared-folder access, and move to Disabled Users')){$processed++;$step='Disable';Disable-ADAccount $user;$step='Reset password';Set-ADAccountPassword $user -Reset -NewPassword (ConvertTo-SecureString (New-IAMRandomPassword 32) -AsPlainText -Force);foreach($g in $remove){$map=$maps|Where-Object DepartmentGroup -eq $g.Name|Select-Object -First 1;Remove-ADGroupMember $g $user -Confirm:$false;Write-IAMLog $logDir 'RBAC-Changes.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;Action='Leaver';GroupName=$g.Name;ChangeType='Removed';PreviousDepartment=$user.Department;MappedDriveRoot=$map.MappedDriveRoot;EntitledFolder=$map.EntitledFolder;AccessLevel=$map.AccessLevel;AccessType='Revoke';ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}};$clear=@();if($ClearManager){$clear+='manager'};if($ClearHomeDriveMapping){$clear+='homeDirectory';$clear+='homeDrive'};if($clear){Set-ADUser $user -Clear $clear};Set-ADUser $user -Description "Disabled by JML $(Get-Date -Format s); Ticket=$($r.TicketID); Operator=$operator";if($oldOU -ne $config.DisabledUsersOU){Move-ADObject $user.DistinguishedName -TargetPath $config.DisabledUsersOU};if($user.HomeDirectory){Write-IAMLog $logDir 'HomeFolder-Report.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;Action='Leaver';HomeFolder=$user.HomeDirectory;HomeDrive=$user.HomeDrive;FolderRetained=$true;FolderArchived=$false;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}};$removed=$remove.Name -join '; ';$revoked=$mapped.EntitledFolder -join '; '
   Write-IAMLog $logDir 'Leaver-Report.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;PreviousDepartment=$user.Department;PreviousJobTitle=$user.Title;PreviousManager=$oldManager;PreviousOU=$oldOU;DisabledUsersOU=$config.DisabledUsersOU;AccountDisabled=$true;PasswordReset=$true;RemovedGroups=$removed;RevokedEntitledFolders=$revoked;HomeFolder=$user.HomeDirectory;HomeFolderRetained=[bool]$user.HomeDirectory;ManagerCleared=[bool]$ClearManager;HomeDriveCleared=[bool]$ClearHomeDriveMapping;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending';Status='Success'};Write-IAMLog $logDir 'JML-Audit.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$user.EmployeeID;SamAccountName=$sam;UserPrincipalName=$user.UserPrincipalName;Action='Leaver';ApprovalStatus=$r.ApprovalStatus;PreviousDepartment=$user.Department;PreviousJobTitle=$user.Title;PreviousManager=$oldManager;PreviousOU=$oldOU;TargetOU=$config.DisabledUsersOU;RemovedGroups=$removed;PreviousEntitledFolders=$revoked;HomeFolder=$user.HomeDirectory;HomeDrive=$user.HomeDrive;Status='Success';Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending'};$success++;$results+=[pscustomobject]@{RequestID=$r.RequestID;SamAccountName=$sam;RemovedGroups=$removed;RevokedEntitledFolders=$revoked;DisabledUsersOU=$config.DisabledUsersOU;Status='Success'}
  }else{$skipped++}
 }catch{$failure++;$msg=$_.Exception.Message;Write-IAMLog $logDir 'Script-Errors.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;ScriptName='Invoke-Leaver.ps1';Action='Leaver';ErrorType=$_.Exception.GetType().FullName;ErrorMessage=$msg;FailedStep=$step;ComputerName=$env:COMPUTERNAME;Technician=$operator};Write-Error $msg}}
 if($success -gt 0 -and -not $WhatIfPreference -and -not $SkipReportRefresh){$refresh=Invoke-IAMReportRefresh $ToolkitRoot}else{$refresh=if($WhatIfPreference){'WhatIf-NoRefresh'}else{'NotRequired'}}
}finally{$end=Get-Date;$result=if($failure){'CompletedWithErrors'}elseif($WhatIfPreference){'WhatIfCompleted'}else{'Success'};Write-IAMLog $logDir 'Execution-History.csv' @{ExecutionID=$executionID;ScriptName='Invoke-Leaver.ps1';StartTime=$start.ToString('o');EndTime=$end.ToString('o');DurationSeconds=[math]::Round(($end-$start).TotalSeconds,2);ComputerName=$env:COMPUTERNAME;Technician=$operator;WhatIfMode=[bool]$WhatIfPreference;RequestsFound=$requests.Count;RequestsProcessed=$processed;SuccessCount=$success;FailureCount=$failure;SkippedCount=$skipped;ReportRefreshResult=$refresh;Result=$result}}
if($PassThru){$results}
