#requires -Version 5.1
#requires -Modules ActiveDirectory
[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='Medium')]
param([string]$ToolkitRoot=(Split-Path $PSScriptRoot -Parent),[int]$PasswordLength=20,[switch]$SkipHomeFolder,[switch]$SkipReportRefresh,[switch]$PassThru)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
Import-Module ActiveDirectory -ErrorAction Stop;Import-Module (Join-Path $ToolkitRoot 'modules\IAM-Common.psm1') -Force
$config=Import-IAMToolkitConfig -Path (Join-Path $ToolkitRoot 'config\IAM-Toolkit-Config.psd1');$requestPath=Join-Path $ToolkitRoot 'input\JML-Requests.csv';$rbacPath=Join-Path $ToolkitRoot 'input\RBAC-Mapping.csv';$logDir=Join-Path $ToolkitRoot 'logs'
Initialize-IAMLogFiles $logDir;$executionID=[guid]::NewGuid().Guid;$start=Get-Date;$operator=Get-IAMOperator;$requests=@();$processed=0;$success=0;$failure=0;$skipped=0;$refresh='NotRun';$results=@()
try{
 $requests=@(Import-Csv $requestPath|Where-Object {$_.Action -eq 'Joiner' -and $_.ApprovalStatus -eq 'Approved'});$mappings=Get-IAMRbacMappings $rbacPath
 foreach($r in $requests){$step='Validation';$sam='';$created=$null;$folder='';try{
  foreach($f in 'RequestID','EmployeeID','FirstName','LastName','JobTitle','Department'){if([string]::IsNullOrWhiteSpace($r.$f)){throw "Required field '$f' is blank."}}
  if(Test-IAMRequestAlreadyCompleted $r.RequestID (Join-Path $logDir 'JML-Audit.csv')){$skipped++;continue}
  if(Get-ADUser -LDAPFilter "(employeeID=$($r.EmployeeID))" -ErrorAction SilentlyContinue){throw "EmployeeID '$($r.EmployeeID)' is already assigned."}
  $map=Get-IAMRbacMapping $r.Department $mappings;$manager=Resolve-IAMManager $r.Manager;$sam=Get-IAMUniqueSamAccountName $r.FirstName $r.LastName $r.SamAccountName;$domain=Get-ADDomain;$upn="$sam@$($domain.DNSRoot)";$display="$($r.FirstName) $($r.LastName)";$plain=New-IAMRandomPassword $PasswordLength;$secure=ConvertTo-SecureString $plain -AsPlainText -Force;$folder=Join-Path $config.HomeFolderAdminRoot $sam;$homeUNC="$($config.HomeFolderUncRoot.TrimEnd('\'))\$sam"
  if(-not $SkipHomeFolder -and -not (Test-Path $config.HomeFolderAdminRoot)){throw "Home-folder root unavailable: $($config.HomeFolderAdminRoot)"}
  if($PSCmdlet.ShouldProcess($upn,"Create Joiner, assign '$($map.DepartmentGroup)', and grant '$($map.EntitledFolder)'")){$processed++;$params=@{Name=$display;GivenName=$r.FirstName;Surname=$r.LastName;DisplayName=$display;SamAccountName=$sam;UserPrincipalName=$upn;EmployeeID=$r.EmployeeID;Title=$r.JobTitle;Department=$r.Department;Path=$map.OU;AccountPassword=$secure;Enabled=$true;ChangePasswordAtLogon=$true;PassThru=$true};if($manager){$params.Manager=$manager.DistinguishedName};if(-not $SkipHomeFolder){$params.HomeDirectory=$homeUNC;$params.HomeDrive=$config.DefaultHomeDrive};$step='Create account';$created=New-ADUser @params;$step='Assign RBAC';Add-ADGroupMember $map.DepartmentGroup $created
   Write-IAMLog $logDir 'RBAC-Changes.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;Action='Joiner';GroupName=$map.DepartmentGroup;ChangeType='Added';Department=$r.Department;MappedDriveRoot=$map.MappedDriveRoot;EntitledFolder=$map.EntitledFolder;AccessLevel=$map.AccessLevel;AccessType=$map.AccessType;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}
   $folderCreated=$false;$aclApplied=$false;if(-not $SkipHomeFolder){$step='Create home folder';New-Item $folder -ItemType Directory -Force|Out-Null;$folderCreated=$true;$step='Apply home ACL';Set-IAMHomeFolderAcl $folder "$($domain.NetBIOSName)\$sam";$aclApplied=$true;Write-IAMLog $logDir 'HomeFolder-Report.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;Action='Joiner';HomeFolder=$homeUNC;HomeDrive=$config.DefaultHomeDrive;FolderCreated=$folderCreated;AclApplied=$aclApplied;Technician=$operator;ComputerName=$env:COMPUTERNAME;Status='Success'}}
   Write-IAMLog $logDir 'Joiner-Report.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;UserPrincipalName=$upn;DisplayName=$display;Department=$r.Department;JobTitle=$r.JobTitle;Manager=if($manager){$manager.Name}else{''};TargetOU=$map.OU;DepartmentGroup=$map.DepartmentGroup;DepartmentMappedDriveRoot=$map.MappedDriveRoot;EntitledFolder=$map.EntitledFolder;DepartmentDriveLetter=$map.DepartmentDriveLetter;SharedDriveAccess=$map.AccessLevel;HomeDirectory=if($SkipHomeFolder){''}else{$homeUNC};HomeDrive=if($SkipHomeFolder){''}else{$config.DefaultHomeDrive};FolderCreated=$folderCreated;AclApplied=$aclApplied;AccountEnabled=$true;ChangePasswordAtLogon=$true;ApprovedBy=$r.ApprovedBy;Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending';Status='Success'}
   Write-IAMLog $logDir 'JML-Audit.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;UserPrincipalName=$upn;Action='Joiner';ApprovalStatus=$r.ApprovalStatus;Department=$r.Department;JobTitle=$r.JobTitle;Manager=if($manager){$manager.Name}else{''};TargetOU=$map.OU;AssignedGroups=$map.DepartmentGroup;DepartmentMappedDriveRoot=$map.MappedDriveRoot;EntitledFolders=$map.EntitledFolder;SharedDriveAccess=$map.AccessLevel;HomeFolder=if($SkipHomeFolder){''}else{$homeUNC};HomeDrive=if($SkipHomeFolder){''}else{$config.DefaultHomeDrive};Status='Success';Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='Pending'}
   $success++;$results+=[pscustomobject]@{RequestID=$r.RequestID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;UPN=$upn;Department=$r.Department;DepartmentGroup=$map.DepartmentGroup;EntitledFolder=$map.EntitledFolder;InitialPassword=$plain;Status='Success'};Write-Host "Created $upn. Initial password (displayed once): $plain" -ForegroundColor Green
  }else{$skipped++}
 }catch{$failure++;$msg=$_.Exception.Message;if($created){try{Remove-ADUser $created -Confirm:$false}catch{}};if($folder -and (Test-Path $folder)){try{Remove-Item $folder -Recurse -Force}catch{}};Write-IAMLog $logDir 'Script-Errors.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;ScriptName='New-Joiner.ps1';Action='Joiner';ErrorType=$_.Exception.GetType().FullName;ErrorMessage=$msg;FailedStep=$step;ComputerName=$env:COMPUTERNAME;Technician=$operator};Write-IAMLog $logDir 'JML-Audit.csv' @{Timestamp=(Get-Date).ToString('o');ExecutionID=$executionID;RequestID=$r.RequestID;TicketID=$r.TicketID;EmployeeID=$r.EmployeeID;SamAccountName=$sam;Action='Joiner';ApprovalStatus=$r.ApprovalStatus;Department=$r.Department;JobTitle=$r.JobTitle;Status='Failed';Technician=$operator;ComputerName=$env:COMPUTERNAME;InventoryRefreshed='No';ErrorMessage=$msg};Write-Error $msg}
 }
 if($success -gt 0 -and -not $WhatIfPreference -and -not $SkipReportRefresh){$refresh=Invoke-IAMReportRefresh $ToolkitRoot}else{$refresh=if($WhatIfPreference){'WhatIf-NoRefresh'}else{'NotRequired'}}
}finally{$end=Get-Date;$result=if($failure){'CompletedWithErrors'}elseif($WhatIfPreference){'WhatIfCompleted'}else{'Success'};Write-IAMLog $logDir 'Execution-History.csv' @{ExecutionID=$executionID;ScriptName='New-Joiner.ps1';StartTime=$start.ToString('o');EndTime=$end.ToString('o');DurationSeconds=[math]::Round(($end-$start).TotalSeconds,2);ComputerName=$env:COMPUTERNAME;Technician=$operator;WhatIfMode=[bool]$WhatIfPreference;RequestsFound=$requests.Count;RequestsProcessed=$processed;SuccessCount=$success;FailureCount=$failure;SkippedCount=$skipped;ReportRefreshResult=$refresh;Result=$result}}
if($PassThru){$results}
